// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1/contract.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	AccountId  string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EntryType  string `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	KeyXdr     []byte `protobuf:"bytes,4,opt,name=key_xdr,json=keyXdr,proto3" json:"key_xdr,omitempty"`
	ValueXdr   []byte `protobuf:"bytes,5,opt,name=value_xdr,json=valueXdr,proto3" json:"value_xdr,omitempty"`
	Durability string `protobuf:"bytes,6,opt,name=durability,proto3" json:"durability,omitempty"`
	Ledger     uint32 `protobuf:"varint,7,opt,name=ledger,proto3" json:"ledger,omitempty"`
	TxHash     string `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	IsNewest   bool   `protobuf:"varint,9,opt,name=is_newest,json=isNewest,proto3" json:"is_newest,omitempty"`
}

func (x *ContractEntry) Reset() {
	*x = ContractEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEntry) ProtoMessage() {}

func (x *ContractEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEntry.ProtoReflect.Descriptor instead.
func (*ContractEntry) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractEntry) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ContractEntry) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *ContractEntry) GetKeyXdr() []byte {
	if x != nil {
		return x.KeyXdr
	}
	return nil
}

func (x *ContractEntry) GetValueXdr() []byte {
	if x != nil {
		return x.ValueXdr
	}
	return nil
}

func (x *ContractEntry) GetDurability() string {
	if x != nil {
		return x.Durability
	}
	return ""
}

func (x *ContractEntry) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *ContractEntry) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ContractEntry) GetIsNewest() bool {
	if x != nil {
		return x.IsNewest
	}
	return false
}

type ContractEntryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *structpb.Struct `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value *structpb.Struct `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ContractEntryInfo) Reset() {
	*x = ContractEntryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractEntryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEntryInfo) ProtoMessage() {}

func (x *ContractEntryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEntryInfo.ProtoReflect.Descriptor instead.
func (*ContractEntryInfo) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractEntryInfo) GetKey() *structpb.Struct {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ContractEntryInfo) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContractEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	KeyXdr     string `protobuf:"bytes,2,opt,name=key_xdr,json=keyXdr,proto3" json:"key_xdr,omitempty"`
}

func (x *ContractEntryRequest) Reset() {
	*x = ContractEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEntryRequest) ProtoMessage() {}

func (x *ContractEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEntryRequest.ProtoReflect.Descriptor instead.
func (*ContractEntryRequest) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ContractEntryRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractEntryRequest) GetKeyXdr() string {
	if x != nil {
		return x.KeyXdr
	}
	return ""
}

type ContractEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *ContractEntryInfo `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Found bool               `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *ContractEntryResponse) Reset() {
	*x = ContractEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEntryResponse) ProtoMessage() {}

func (x *ContractEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEntryResponse.ProtoReflect.Descriptor instead.
func (*ContractEntryResponse) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ContractEntryResponse) GetEntry() *ContractEntryInfo {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ContractEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ContractDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Page       int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ContractDataRequest) Reset() {
	*x = ContractDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDataRequest) ProtoMessage() {}

func (x *ContractDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDataRequest.ProtoReflect.Descriptor instead.
func (*ContractDataRequest) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ContractDataRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ContractDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ContractEntryInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page int32                `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ContractDataResponse) Reset() {
	*x = ContractDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDataResponse) ProtoMessage() {}

func (x *ContractDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDataResponse.ProtoReflect.Descriptor instead.
func (*ContractDataResponse) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ContractDataResponse) GetData() []*ContractEntryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContractDataResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ContractKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (x *ContractKeysRequest) Reset() {
	*x = ContractKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractKeysRequest) ProtoMessage() {}

func (x *ContractKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractKeysRequest.ProtoReflect.Descriptor instead.
func (*ContractKeysRequest) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ContractKeysRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type ContractKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*structpb.Struct `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ContractKeysResponse) Reset() {
	*x = ContractKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractKeysResponse) ProtoMessage() {}

func (x *ContractKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractKeysResponse.ProtoReflect.Descriptor instead.
func (*ContractKeysResponse) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{7}
}

func (x *ContractKeysResponse) GetKeys() []*structpb.Struct {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UserInteractionContractsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UserInteractionContractsRequest) Reset() {
	*x = UserInteractionContractsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInteractionContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInteractionContractsRequest) ProtoMessage() {}

func (x *UserInteractionContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInteractionContractsRequest.ProtoReflect.Descriptor instead.
func (*UserInteractionContractsRequest) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{8}
}

func (x *UserInteractionContractsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserInteractionContractsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contracts []string `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
}

func (x *UserInteractionContractsResponse) Reset() {
	*x = UserInteractionContractsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInteractionContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInteractionContractsResponse) ProtoMessage() {}

func (x *UserInteractionContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInteractionContractsResponse.ProtoReflect.Descriptor instead.
func (*UserInteractionContractsResponse) Descriptor() ([]byte, []int) {
	return file_v1_contract_proto_rawDescGZIP(), []int{9}
}

func (x *UserInteractionContractsResponse) GetContracts() []string {
	if x != nil {
		return x.Contracts
	}
	return nil
}

var File_v1_contract_proto protoreflect.FileDescriptor

var file_v1_contract_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x78, 0x64,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x58, 0x64, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x78, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x58, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x11, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x29, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x78, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x58, 0x64, 0x72, 0x22, 0x5a, 0x0a, 0x15, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x43, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4b, 0x65,
	0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x3b, 0x0a, 0x1f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x40, 0x0a, 0x20, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x42, 0x68, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x31,
	0x42, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x63, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x72, 0x6f, 0x62, 0x6f, 0x6f, 0x6b,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58,
	0xaa, 0x02, 0x02, 0x56, 0x31, 0xca, 0x02, 0x02, 0x56, 0x31, 0xe2, 0x02, 0x0e, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_contract_proto_rawDescOnce sync.Once
	file_v1_contract_proto_rawDescData = file_v1_contract_proto_rawDesc
)

func file_v1_contract_proto_rawDescGZIP() []byte {
	file_v1_contract_proto_rawDescOnce.Do(func() {
		file_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_contract_proto_rawDescData)
	})
	return file_v1_contract_proto_rawDescData
}

var file_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_contract_proto_goTypes = []interface{}{
	(*ContractEntry)(nil),                    // 0: v1.ContractEntry
	(*ContractEntryInfo)(nil),                // 1: v1.ContractEntryInfo
	(*ContractEntryRequest)(nil),             // 2: v1.ContractEntryRequest
	(*ContractEntryResponse)(nil),            // 3: v1.ContractEntryResponse
	(*ContractDataRequest)(nil),              // 4: v1.ContractDataRequest
	(*ContractDataResponse)(nil),             // 5: v1.ContractDataResponse
	(*ContractKeysRequest)(nil),              // 6: v1.ContractKeysRequest
	(*ContractKeysResponse)(nil),             // 7: v1.ContractKeysResponse
	(*UserInteractionContractsRequest)(nil),  // 8: v1.UserInteractionContractsRequest
	(*UserInteractionContractsResponse)(nil), // 9: v1.UserInteractionContractsResponse
	(*structpb.Struct)(nil),                  // 10: google.protobuf.Struct
}
var file_v1_contract_proto_depIdxs = []int32{
	10, // 0: v1.ContractEntryInfo.key:type_name -> google.protobuf.Struct
	10, // 1: v1.ContractEntryInfo.value:type_name -> google.protobuf.Struct
	1,  // 2: v1.ContractEntryResponse.entry:type_name -> v1.ContractEntryInfo
	1,  // 3: v1.ContractDataResponse.data:type_name -> v1.ContractEntryInfo
	10, // 4: v1.ContractKeysResponse.keys:type_name -> google.protobuf.Struct
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_contract_proto_init() }
func file_v1_contract_proto_init() {
	if File_v1_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractEntryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInteractionContractsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInteractionContractsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_contract_proto_goTypes,
		DependencyIndexes: file_v1_contract_proto_depIdxs,
		MessageInfos:      file_v1_contract_proto_msgTypes,
	}.Build()
	File_v1_contract_proto = out.File
	file_v1_contract_proto_rawDesc = nil
	file_v1_contract_proto_goTypes = nil
	file_v1_contract_proto_depIdxs = nil
}
