// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: contract/code.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId     string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	CreatorAddress string `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	ContractCode   string `protobuf:"bytes,3,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	CreatedLedger  uint32 `protobuf:"varint,4,opt,name=created_ledger,json=createdLedger,proto3" json:"created_ledger,omitempty"`
}

func (x *ContractCode) Reset() {
	*x = ContractCode{}
	mi := &file_contract_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCode) ProtoMessage() {}

func (x *ContractCode) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCode.ProtoReflect.Descriptor instead.
func (*ContractCode) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{0}
}

func (x *ContractCode) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractCode) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *ContractCode) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *ContractCode) GetCreatedLedger() uint32 {
	if x != nil {
		return x.CreatedLedger
	}
	return 0
}

type ContractCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
}

func (x *ContractCodeRequest) Reset() {
	*x = ContractCodeRequest{}
	mi := &file_contract_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCodeRequest) ProtoMessage() {}

func (x *ContractCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCodeRequest.ProtoReflect.Descriptor instead.
func (*ContractCodeRequest) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{1}
}

func (x *ContractCodeRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type ContractCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract *ContractCode `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Found    bool          `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *ContractCodeResponse) Reset() {
	*x = ContractCodeResponse{}
	mi := &file_contract_code_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCodeResponse) ProtoMessage() {}

func (x *ContractCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCodeResponse.ProtoReflect.Descriptor instead.
func (*ContractCodeResponse) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{2}
}

func (x *ContractCodeResponse) GetContract() *ContractCode {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ContractCodeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ContractCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ContractCodesRequest) Reset() {
	*x = ContractCodesRequest{}
	mi := &file_contract_code_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCodesRequest) ProtoMessage() {}

func (x *ContractCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCodesRequest.ProtoReflect.Descriptor instead.
func (*ContractCodesRequest) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{3}
}

func (x *ContractCodesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContractCodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ContractCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ContractCode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ContractCodesResponse) Reset() {
	*x = ContractCodesResponse{}
	mi := &file_contract_code_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCodesResponse) ProtoMessage() {}

func (x *ContractCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCodesResponse.ProtoReflect.Descriptor instead.
func (*ContractCodesResponse) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{4}
}

func (x *ContractCodesResponse) GetData() []*ContractCode {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContractsAtLedgerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ledger   uint32 `protobuf:"varint,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ContractsAtLedgerRequest) Reset() {
	*x = ContractsAtLedgerRequest{}
	mi := &file_contract_code_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractsAtLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractsAtLedgerRequest) ProtoMessage() {}

func (x *ContractsAtLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractsAtLedgerRequest.ProtoReflect.Descriptor instead.
func (*ContractsAtLedgerRequest) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{5}
}

func (x *ContractsAtLedgerRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *ContractsAtLedgerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContractsAtLedgerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ContractsAtLedgerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ContractCode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ContractsAtLedgerResponse) Reset() {
	*x = ContractsAtLedgerResponse{}
	mi := &file_contract_code_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractsAtLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractsAtLedgerResponse) ProtoMessage() {}

func (x *ContractsAtLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_code_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractsAtLedgerResponse.ProtoReflect.Descriptor instead.
func (*ContractsAtLedgerResponse) Descriptor() ([]byte, []int) {
	return file_contract_code_proto_rawDescGZIP(), []int{6}
}

func (x *ContractsAtLedgerResponse) GetData() []*ContractCode {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_contract_code_proto protoreflect.FileDescriptor

var file_contract_code_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22,
	0xa4, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x22, 0x60,
	0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x22, 0x47, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63,
	0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x41, 0x74, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x47, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x41, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x8b, 0x01, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x09, 0x43,
	0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x6f,
	0x2f, 0x73, 0x6f, 0x72, 0x6f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xa2, 0x02, 0x03, 0x43,
	0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xca, 0x02, 0x08,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xe2, 0x02, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_contract_code_proto_rawDescOnce sync.Once
	file_contract_code_proto_rawDescData = file_contract_code_proto_rawDesc
)

func file_contract_code_proto_rawDescGZIP() []byte {
	file_contract_code_proto_rawDescOnce.Do(func() {
		file_contract_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_code_proto_rawDescData)
	})
	return file_contract_code_proto_rawDescData
}

var file_contract_code_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contract_code_proto_goTypes = []any{
	(*ContractCode)(nil),              // 0: contract.ContractCode
	(*ContractCodeRequest)(nil),       // 1: contract.ContractCodeRequest
	(*ContractCodeResponse)(nil),      // 2: contract.ContractCodeResponse
	(*ContractCodesRequest)(nil),      // 3: contract.ContractCodesRequest
	(*ContractCodesResponse)(nil),     // 4: contract.ContractCodesResponse
	(*ContractsAtLedgerRequest)(nil),  // 5: contract.ContractsAtLedgerRequest
	(*ContractsAtLedgerResponse)(nil), // 6: contract.ContractsAtLedgerResponse
}
var file_contract_code_proto_depIdxs = []int32{
	0, // 0: contract.ContractCodeResponse.contract:type_name -> contract.ContractCode
	0, // 1: contract.ContractCodesResponse.data:type_name -> contract.ContractCode
	0, // 2: contract.ContractsAtLedgerResponse.data:type_name -> contract.ContractCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contract_code_proto_init() }
func file_contract_code_proto_init() {
	if File_contract_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_code_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_code_proto_goTypes,
		DependencyIndexes: file_contract_code_proto_depIdxs,
		MessageInfos:      file_contract_code_proto_msgTypes,
	}.Build()
	File_contract_code_proto = out.File
	file_contract_code_proto_rawDesc = nil
	file_contract_code_proto_goTypes = nil
	file_contract_code_proto_depIdxs = nil
}
