version: v1

plugins:
  - name: grpc-gateway
    out: .
    opt:
      - logtostderr=true
  - plugin: buf.build/grpc-ecosystem/openapiv2:v2.19.1
    out: ../tmp-swagger-gen
    opt:
      - logtostderr=true
      - simple_operation_ids=true